# -*- coding: utf-8 -*-
"""Group044_ass2_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16khRSyDAcVXd2ZRonstduBjepLKL-vGe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ast

from google.colab import drive
drive.mount('/content/drive')

missing_df = pd.read_csv('/content/drive/Shareddrives/FIT5196_S2_2025/Assessment2/student_data/Group044/Group_044_missing_data.csv')

dirty_df = pd.read_csv('/content/drive/Shareddrives/FIT5196_S2_2025/Assessment2/student_data/Group044/Group_044_dirty_data.csv')

outlier_df = pd.read_csv('/content/drive/Shareddrives/FIT5196_S2_2025/Assessment2/student_data/Group044/Group_044_outlier_data.csv')

warehouse_df = pd.read_csv('/content/drive/Shareddrives/FIT5196_S2_2025/Assessment2/warehouses.csv')

"""# Missing Data Handling

## EDA analysis on missing data
"""

# Show first 5 rows of dataset

missing_df.head()

# Show total rows and columns of dataset

missing_df.shape

missing_df.info()

# Show all the column names of the dataset
missing_df.columns

# Show data types of each column
missing_df.dtypes

# Checking for missing values
missing_df.isna().sum()

# Checking if any duplicate columns
missing_df.duplicated().sum()

missing_df.describe()

missing_df.describe(include='object')

"""To assess data completeness, .info() and .isna().sum() were used to identify missing values across all columns. The dataset contains 500 records and 16 features. Several columns had missing values, most notably nearest_warehouse (55), delivery_charges (40), is_happy_customer (40), distance_to_nearest_warehouse (31), order_price (15), and order_total (15). Descriptive statistics were generated to understand the distribution of both numerical and categorical data before deciding on suitable imputation strategies.

This analysis established a clear view of where data gaps exist, their magnitude, and the types of variables affected, providing a solid foundation for the next step, which was deciding whether to impute or remove missing entries based on their importance and proportion.
"""

# Display frequency counts for key categorical variables to understand their distribution
# This helps identify class imbalance or rare categories in columns like season, delivery type, customer satisfaction, and nearest warehouse

missing_df["season"].value_counts()

missing_df["is_expedited_delivery"].value_counts()

missing_df["is_happy_customer"].value_counts()

missing_df["nearest_warehouse"].value_counts()

"""To better understand the distribution of categorical data and identify potential biases, value counts were computed for variables such as season, is_expedited_delivery, is_happy_customer, and nearest_warehouse. The results show that Spring (151) and Winter (131) orders are most common, while Summer (104) is least frequent. Delivery type is nearly balanced with 244 expedited and 256 standard deliveries, suggesting no delivery-type bias. The majority of customers (353) reported being happy with their purchase, compared to 107 unhappy customers. Additionally, Thompson (175) was the most frequently used warehouse, followed by Nickolson (159) and Bakers (111).

This step helped identify dominant categories and ensured categorical variables were well understood before handling missing values and performing further preprocessing.
"""

# Visualise the distribution and outliers in order_price
sns.boxplot(y="order_price", data=missing_df)

# Compare delivery_charges across different nearest warehouses
sns.boxplot(y="delivery_charges", x="nearest_warehouse", data=missing_df)

# Examine how distance_to_nearest_warehouse varies by warehouse location
sns.boxplot(y="distance_to_nearest_warehouse", x="nearest_warehouse", data=missing_df)

# Plot bar chart to show proportion of happy vs unhappy customers
missing_df["is_happy_customer"].value_counts().plot(kind="bar")

"""Boxplots were used to examine the distribution and potential outliers in order_price, delivery_charges, and distance_to_nearest_warehouse, while a bar plot was used to visualize customer satisfaction.

The order_price boxplot shows a moderately right-skewed distribution with a few high-value outliers above 35,000, suggesting some premium orders. delivery_charges, grouped by nearest_warehouse, show similar medians across warehouses, with slight variation, Thompson having marginally higher charges on average. The distance_to_nearest_warehouse plot reveals that Nickolson generally serves closer customers, while Bakers covers longer distances. Finally, the is_happy_customer bar plot indicates that the majority of customers are satisfied, reflecting a positive customer experience overall.

This visual exploration helped identify data variability, detect outliers, and understand the relationships between warehouse operations, pricing, and customer satisfaction.

## 1. Fixing missing values in nearest_warehouse ##
"""

# Define a Haversine function to calculate great-circle distance between two coordinates (in km)
def haversine(lat1, lon1, lat2, lon2):
    R = 6378  # Earth's radius in km
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    return R * c

# Find the nearest warehouse to a given customer location using Haversine distance
def find_nearest_warehouse(lat, lon, warehouses):
    distances = warehouses.apply(
        lambda w: haversine(lat, lon, w['lat'], w['lon']), axis=1
    )
    nearest_idx = distances.idxmin()
    return warehouses.loc[nearest_idx, 'names']  # adjust if column name differs

# Identify and fill missing nearest_warehouse values based on customer coordinates
mask_missing = missing_df['nearest_warehouse'].isna()
missing_df.loc[mask_missing, 'nearest_warehouse'] = missing_df.loc[mask_missing].apply(
    lambda row: find_nearest_warehouse(row['customer_lat'], row['customer_long'], warehouse_df),
    axis=1
)

# Verify that all missing nearest_warehouse values have been filled
missing_df['nearest_warehouse'].isna().sum()

# Check dataset dimensions
missing_df.shape

# Check dataset dimensions and missing values across all columns
missing_df.isna().sum()

"""The missing nearest_warehouse values were imputed using a distance-based approach. A haversine() function was implemented to calculate the great-circle distance (in kilometers) between a customer’s latitude and longitude coordinates and each warehouse’s location. Then, the helper function find_nearest_warehouse() identified the closest warehouse for each customer by selecting the warehouse with the smallest calculated distance.

This method ensures that missing warehouse values are filled logically and geographically rather than randomly or by frequency. After imputation, all missing entries in nearest_warehouse were successfully resolved (0 remaining nulls), improving the dataset’s integrity for further analysis.

## 2.& 3. Fixing missing values in shopping_cart and order_price
"""

# Parse shopping_cart column from string to list of tuples
def parse_cart(cell):
  try:
    return ast.literal_eval(cell) if isinstance(cell, str) else cell
  except Exception:
    return []

# Apply parsing function to create a new column with structured cart data
missing_df["parsed_cart"] = missing_df["shopping_cart"].apply(parse_cart)

# Extract unique item names from all carts and assign index positions
items = sorted({item for cart in missing_df["parsed_cart"] for (item, qty) in cart})
item_to_idx = {item: i for i, item in enumerate(items)}

item_to_idx

missing_df["parsed_cart"]

#Build feature matrix (X) and target vector (y) for known order_price entries
mask_known = missing_df["order_price"].notna()
X_list, y_list = [], []

for idx, row in missing_df[mask_known].iterrows():
    vec = np.zeros(len(items))
    for (item, qty) in row["parsed_cart"]:
        vec[item_to_idx[item]] += qty
    X_list.append(vec)
    y_list.append(row["order_price"])

X = np.array(X_list)
y = np.array(y_list)

print(X)

print(y)

# Estimate unit prices using least squares regression
unit_prices = np.linalg.lstsq(X, y, rcond=None)[0]

# Create dictionary mapping each item to its estimated unit price
unit_price_map = {item: price for item, price in zip(items, unit_prices)}
print("Learned unit prices:")
for k,v in unit_price_map.items():
    print(f"{k}: {v:.2f}")

# Fill missing order_price values using learned unit prices
mask_missing = missing_df["order_price"].isna()
for idx, row in missing_df[mask_missing].iterrows():
    total = 0
    for (item, qty) in row["parsed_cart"]:
        if item in unit_price_map:
            total += unit_price_map[item] * qty
        else:
            total = np.nan  # if an unseen item, leave as NaN
            break
    missing_df.at[idx, "order_price"] = total

# Verify that all missing order_price values have been filled
missing_df.isna().sum()

"""The shopping_cart column originally contained string representations of lists, making it difficult to extract product and quantity information. To address this, a parsing function (parse_cart) was created to safely convert each string into a list of item–quantity tuples. This allowed the contents of each customer’s cart to be structured in a usable format under a new column parsed_cart.

Next, the unit prices of individual products were estimated using a linear least squares regression approach. A matrix (X) was constructed where each row represented the quantities of all items in an order, and the corresponding y vector contained known order prices. Solving the system using np.linalg.lstsq() produced a unit price for each product.

Using these learned unit prices, the missing order_price values were then imputed by summing the estimated cost of each product in the customer’s parsed cart. This method provides a data-driven and interpretable imputation rather than relying on arbitrary averages.

Finally, verification with missing_df.isna().sum() confirmed that all missing values in both shopping_cart and order_price were successfully resolved.

## 4.& 5. Fixing missing values in delivery_charges and order_total
"""

# Prepare input features for regression model
def prep_features(df: pd.DataFrame) -> pd.DataFrame:
    X = pd.DataFrame(index=df.index)

    # Base numeric and binary features
    X["distance"]  = pd.to_numeric(df["distance_to_nearest_warehouse"], errors="coerce")
    X["expedited"] = df["is_expedited_delivery"].astype(bool).astype(int)
    X["happy"]     = df["is_happy_customer"].astype(bool).astype(int)

    # One-hot encoding season column (drop first to avoid multicollinearity)
    seasons = pd.get_dummies(df["season"], prefix="season", drop_first=True)
    X = pd.concat([X, seasons], axis=1)

    # Create interaction terms to allow season-specific effects
    for col in seasons.columns:
        X[f"{col}__distance"]  = seasons[col] * X["distance"]
        X[f"{col}__expedited"] = seasons[col] * X["expedited"]
        X[f"{col}__happy"]     = seasons[col] * X["happy"]

    # Replace infinite values with NaN
    X = X.replace([np.inf, -np.inf], np.nan)
    return X

# Select rows with complete data for training
mask_train = (
    missing_df["delivery_charges"].notna()
    & missing_df["distance_to_nearest_warehouse"].notna()
    & missing_df["is_expedited_delivery"].notna()
    & missing_df["is_happy_customer"].notna()
    & missing_df["season"].notna()
)

# Prepare training data and target
X_train = prep_features(missing_df.loc[mask_train].copy())
y_train = missing_df.loc[mask_train, "delivery_charges"].astype(float)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Train linear regression model to predict delivery_charges
model = LinearRegression()
model.fit(X_train, y_train)

# Evaluate model performance
r2 = r2_score(y_train, model.predict(X_train))
print(f"R²: {r2:.4f}")

# Predict and fill missing delivery_charges
mask_pred = missing_df["delivery_charges"].isna()
if mask_pred.any():
    X_pred = prep_features(missing_df.loc[mask_pred])
    missing_df.loc[mask_pred, "delivery_charges"] = model.predict(X_pred)

missing_df.isna().sum()

missing_df.shape

# Recalculate order_total for missing values based on known fields
mask_total = missing_df["order_total"].isna() & missing_df["order_price"].notna() & missing_df["delivery_charges"].notna()

if mask_total.any():
    missing_df.loc[mask_total, "order_total"] = (
        missing_df.loc[mask_total, "order_price"] * (1 - (missing_df.loc[mask_total, "coupon_discount"].fillna(0) / 100.0))
        + missing_df.loc[mask_total, "delivery_charges"]
    )

# Confirm final dataset shape and no remaining missing values
missing_df.shape

missing_df.loc[27, ]

"""To address missing values in the delivery_charges column, a supervised learning approach was applied using a multiple linear regression model. This model estimated delivery costs based on relevant operational and behavioral factors rather than relying on simple averages or assumptions.

A function, prep_features(), was first created to prepare input variables for modelling. It included key predictors such as:

* distance_to_nearest_warehouse: the most direct determinant of delivery cost

* is_expedited_delivery: indicating whether express delivery was selected

* is_happy_customer: representing satisfaction or loyalty that might influence delivery discounts

* season: to capture potential seasonal variations in delivery pricing

The function also implemented one-hot encoding for the season variable, with one category dropped to prevent multicollinearity and introduced interaction terms between season and other variables such as season_Winter__distance, season_Summer__expedited. These interactions allowed the model to learn how delivery costs behave differently across seasons and delivery types.

Using these engineered features, a Linear Regression model from scikit-learn was trained on all complete records. The resulting model achieved a very high fit (R² = 0.9948), indicating excellent explanatory power. The model was then used to impute the missing delivery_charges values, ensuring the estimates were consistent with real-world patterns observed in the dataset.

Following this, the order_total column was recalculated using a derived formula that reflects how total order values are typically computed in practice:

order_total=(order_price×(1−coupon_discount/100))+delivery_charges

This calculation integrates the effects of item prices, discounts, and delivery costs in a coherent manner. A verification step using missing_df.isna().sum() confirmed that all missing values for both delivery_charges and order_total had been successfully filled.

Overall, this approach demonstrates a data-driven, interpretable, and consistent strategy for imputing missing values, maintaining both statistical accuracy and business logic integrity across the dataset.

## 6. Fixing missing values in distance_to_nearest_warehouse
"""

# Define function to find the shortest distance from a customer to any warehouse
def find_nearest_warehouse_distance(lat, lon, warehouses):
    distances = warehouses.apply(
        lambda w: haversine(lat, lon, w['lat'], w['lon']), axis=1
    )
    return round(min(distances), 4)

# Identify rows with missing distance_to_nearest_warehouse values
mask_missing = missing_df['distance_to_nearest_warehouse'].isna()

# Fill missing distances using the haversine-based nearest warehouse distance
missing_df.loc[mask_missing, 'distance_to_nearest_warehouse'] = missing_df.loc[mask_missing].apply(
    lambda row: find_nearest_warehouse_distance(row['customer_lat'], row['customer_long'], warehouse_df),
    axis=1
)

# Verify all missing values in distance_to_nearest_warehouse are fixed
missing_df.isna().sum()

# Confirm dataset shape remains unchanged
missing_df.shape

"""To handle missing values in the distance_to_nearest_warehouse column, a spatial calculation approach was used to ensure realistic and data-consistent imputation. A helper function, find_nearest_warehouse_distance(), was created to compute the shortest distance (in kilometers) between each customer’s coordinates and all available warehouse coordinates using the Haversine formula. This formula calculates great-circle distances based on latitude and longitude, making it appropriate for geographic data.

For each record with a missing distance, the code applied this function to find the minimum calculated distance to any warehouse and assigned that value back to the dataset, rounded to four decimal places for precision. This approach ensures that all imputed distances reflect actual geographic proximity rather than arbitrary or average estimates.

A final validation step (missing_df.isna().sum()) confirmed that all missing entries in the distance_to_nearest_warehouse column were successfully filled, resulting in a complete dataset with 500 rows and 17 columns (will remove extra column later on), and no remaining missing values.

## 7. Fixing missing values in is_happy_customer
"""

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

# Initialise the sentiment analyser
sid = SentimentIntensityAnalyzer()

# Identify rows where is_happy_customer is missing
mask_happy = missing_df["is_happy_customer"].isna()

if mask_happy.any():
    # Compute VADER compound score for each missing row's latest review (empty string if NaN)
    scores = missing_df.loc[mask_happy, "latest_customer_review"].fillna("").astype(str).apply(
        lambda text: sid.polarity_scores(text)["compound"]
    )

# Impute is_happy_customer based on sentiment: True if compound >= 0.05, else False
missing_df.loc[mask_happy, "is_happy_customer"] = scores >= 0.05

# Ensure the column is boolean-typed

missing_df["is_happy_customer"] = missing_df["is_happy_customer"].astype(bool)

# confirm no remaining missing values across columns
missing_df.isna().sum()

# Remove helper parsed_cart column, no longer needed
missing_df = missing_df.drop(columns=['parsed_cart'])

# Verify final shape after cleanup
missing_df.shape

# Inspect class balance after imputation
missing_df["is_happy_customer"].value_counts()

#  Quick preview of the cleaned dataset
missing_df.head()

"""In this step, the missing values in the is_happy_customer column were filled using sentiment analysis on customer reviews. Since this column represents whether a customer is satisfied or not, the latest_customer_review text data was used to infer their happiness level.

Sentiment Analysis with VADER (NLTK):

* The VADER model from the NLTK library was used to analyze the emotional tone of each review.

* The compound sentiment score (ranging from -1 to +1) was computed for each missing entry.

* Reviews with a compound score ≥ 0.05 were classified as happy customers (True), while others were classified as not happy (False).

Handling Missing or Neutral Reviews:

* Missing reviews were replaced with empty strings ("") before analysis.

* These generally resulted in a compound score close to zero, and were therefore categorized as not happy.

Data Type Conversion and Final Checks:

* After classification, the column was explicitly converted to a boolean data type (True or False).

* The final check showed no remaining missing values across the entire dataset.

* The distribution was: 384 happy customers and 116 unhappy customers.

This approach ensured that the is_happy_customer column was filled logically based on the sentiment of customers’ written feedback, allowing for more accurate downstream analysis of customer satisfaction.

## Replotting and verifying after fixing missing values
"""

sns.boxplot(y="order_price", data=missing_df)

sns.boxplot(y="delivery_charges", x="nearest_warehouse", data=missing_df)

sns.boxplot(y="distance_to_nearest_warehouse", x="nearest_warehouse", data=missing_df)

missing_df["is_happy_customer"].value_counts().plot(kind="bar")

"""After completing all imputation steps, boxplots were replotted to visually check that the corrected data behaved realistically and that no new anomalies were introduced.

Order Price Distribution:
The boxplot for order_price shows a reasonable range of prices mostly between $8,000 – $20,000, with a few higher values up to around $40,000.
The outliers above this range are consistent with high-value orders and not data-entry errors. This confirms that the imputation of order_price using learned unit prices produced plausible results.

Delivery Charges by Warehouse:
The boxplot of delivery_charges grouped by nearest_warehouse demonstrates that all three warehouses (Bakers, Thompson, and Nickolson) have very similar distributions, centred around $70–$80 with minor variation.
A few higher values near $110 were observed but remain reasonable, suggesting the regression-based imputation maintained realistic variability.

Distance to Nearest Warehouse:
The distance_to_nearest_warehouse boxplot shows that average customer distance varies slightly by warehouse, with Bakers generally having longer distances.
The overall range (approximately 0 – 2.5 km) aligns with expected delivery zones, confirming that distance calculations using the Haversine formula were performed correctly.

Overall, the re-plotted boxplots confirm that all imputations were successful, the distributions look natural, the outliers are legitimate, and no new missing or inconsistent values were introduced. The dataset is now complete and ready for further analysis in subsequent tasks.

# Outlier Data Handling

## EDA analysis on missing data
"""

# Preview the first few rows of the dataset
outlier_df.head()

# Check dataset dimensions to verify the number of rows and columns
outlier_df.shape

# Confirm there are no missing values across all columns
outlier_df.isna().sum()

# Display column names to verify expected attributes are present

outlier_df.columns

# Check data types of each column to ensure correct format before analysis
outlier_df.dtypes

# Generate summary statistics for numerical columns to detect potential outliers
outlier_df.describe()

# Generate summary statistics for categorical columns to understand unique values and frequency
outlier_df.describe(include='object')

# Check for duplicate rows to ensure dataset uniqueness and integrity
outlier_df.duplicated().sum()

"""The outlier dataset was first explored to understand its structure and content before proceeding with detection steps. The dataset contained 500 rows and 16 columns, each representing a customer order with information such as order details, delivery costs, warehouse location, and review sentiment. No missing values were identified across any variables, confirming the dataset’s completeness. The column inspection verified the presence of both numerical and categorical attributes, including order_price, delivery_charges, customer_lat, and season, ensuring all required fields were retained.

Descriptive statistics revealed that the average order price was approximately 13,750, ranging from 1,375 to 39,290, which suggested the presence of high-value orders that might be potential outliers. Delivery charges averaged around 77, varying between 23.55 and 157.78, while distances to the nearest warehouse ranged between 0.04 and 2.89 km,values that appeared reasonable within expected delivery ranges. Coupon discounts ranged from 0 to 25, confirming valid promotional values. The latitude and longitude data were consistent and within Melbourne’s geographic range, indicating no coordinate errors.

For categorical features, there were three warehouse locations (Bakers, Thompson, and Nickolson) and four valid seasons (Summer, Autumn, Winter, and Spring), showing balanced representation. There were 455 unique shopping carts, implying a high level of product diversity, and all 500 customer reviews were unique, confirming no repetition in text data. The duplication check using .duplicated().sum() returned zero, confirming all records were unique.

## Outlier Detection using Z-score Method
"""

from scipy.stats import zscore

# Select numeric columns to check for outliers
num_cols = ["order_price","delivery_charges","order_total","coupon_discount","distance_to_nearest_warehouse"]

# Compute z-scores for each numeric column
z_scores = outlier_df[num_cols].apply(zscore)

# Create a boolean mask where |z| > 3 (threshold for outliers)
outliers_per_col = (z_scores.abs() > 3)

# Display how many outliers exist in each column
print("Outlier counts per column:")
print(outliers_per_col.sum())

# Identify all rows that contain at least one outlier
outlier_rows = outlier_df.loc[outliers_per_col.any(axis=1)]
print("\nTotal outlier rows:", outlier_rows.shape[0])

# Print the specific row indices where outliers occur in each column
for col in num_cols:
    outlier_idx = outlier_df.index[outliers_per_col[col]].tolist()
    print(f"{col}: {len(outlier_idx)} outliers at rows {outlier_idx}")

"""To identify potential outliers in the dataset, the Z-score method from the SciPy library was applied to the numerical columns: order_price, delivery_charges, order_total, coupon_discount, and distance_to_nearest_warehouse. The Z-score measures how far a data point deviates from the mean in terms of standard deviations. Any record with an absolute Z-score greater than 3 was classified as an outlier. The results showed that there were a total of 13 outlier rows across the dataset. Specifically, order_price had 2 outliers located at rows 443 and 477, delivery_charges contained 7 outliers across rows 38, 109, 258, 310, 331, 364, and 436, order_total had 3 outliers at rows 121, 443, and 477, and distance_to_nearest_warehouse had 3 outliers at rows 296, 450, and 478. No outliers were detected in coupon_discount, suggesting discounts were applied within normal promotional ranges. These findings indicate that a few transactions had unusually high order prices or delivery charges compared to the rest of the data, which may warrant further investigation or capping during the data cleaning phase to prevent distortion in model performance."""

# Compute correlation matrix for numeric columns to identify linear relationships
# Helps detect strong correlations
outlier_df[num_cols].corr()

"""A correlation analysis was conducted on the numerical variables to examine the strength and direction of relationships between them. The results showed that order_price and order_total were highly positively correlated (0.98), which is expected since higher order prices directly increase total order values. Delivery_charges showed only weak correlations with other variables, suggesting that shipping costs are relatively independent of order prices or discounts. Coupon_discount had a weak negative relationship with order_total (-0.12), implying that higher discounts slightly reduce the total order value. Additionally, distance_to_nearest_warehouse showed minimal correlation with most variables, indicating that delivery distance does not strongly influence order cost or price. Overall, the correlation results confirm that most numerical features are largely independent, except for the expected strong relationship between order price and order total."""

# For categorical columns
# Check the distribution of orders across warehouses
# to identify which location processes the most orders
outlier_df["nearest_warehouse"].value_counts()

# Check the seasonal distribution of orders
# to observe if data is balanced or skewed toward specific seasons
outlier_df["season"].value_counts()

# Examine frequency of expedited vs standard deliveries
# to understand delivery speed preferences among customers
outlier_df["is_expedited_delivery"].value_counts()

# Examine frequency of expedited vs standard deliveries
# to understand delivery speed preferences among customers
outlier_df["is_happy_customer"].value_counts()

"""The categorical variable distribution was analyzed to understand the frequency of values across key non-numeric fields. For nearest_warehouse, the majority of orders were processed through the Thompson warehouse (207), followed by Nickolson (183) and Bakers (110), indicating that Thompson handles the highest order volume. For the season variable, orders were relatively evenly distributed throughout the year, with a slight increase in Summer (133) and a minor decrease during Winter (121). The is_expedited_delivery variable showed a nearly balanced split between expedited and non-expedited deliveries, with 259 and 241 orders respectively, suggesting consistent demand for both delivery types. Lastly, the is_happy_customer column showed that 376 customers were happy compared to 124 unhappy customers, demonstrating a generally positive sentiment across the customer base. These distributions provide an overview of order patterns, seasonal effects, and customer satisfaction trends within the dataset.

## Visualisation of outliers
"""

# Boxplot to visualize the distribution of delivery charges
# Identifies central tendency (median) and highlights potential outliers
sns.boxplot(y="delivery_charges", data=outlier_df, color="coral")

# Scatter plot to examine the relationship between delivery charges and distance
# Each point represents an order,  helps reveal whether higher distances lead to higher charges
plt.figure(figsize=(6,4))
sns.scatterplot(
    x=outlier_df["distance_to_nearest_warehouse"],
    y=outlier_df["delivery_charges"],
    alpha=0.7
)
plt.title("Delivery Charges vs Distance to Nearest Warehouse")
plt.xlabel("Distance to Nearest Warehouse (km)")
plt.ylabel("Delivery Charges")
plt.show()

"""The boxplot for delivery_charges reveals that most delivery fees range between approximately 65 and 85, with a median around 75. However, several outliers are present both below and above this range, particularly in the upper region beyond 110, indicating that a small number of deliveries are significantly more expensive than the rest. This suggests variability in pricing, possibly due to distance or service type differences.

The scatter plot examining the relationship between delivery_charges and distance_to_nearest_warehouse shows a weak positive trend, where delivery charges slightly increase with distance. However, the relationship is not strong or linear, as there is considerable spread in the data across all distances. This indicates that while distance contributes somewhat to delivery cost, other factors such as warehouse policies, order volume, or delivery urgency, likely influence the final charge.
"""

# Ensure numeric types for correlation analysis
# Convert columns to appropriate numeric or boolean types to avoid computation errors
missing_df["delivery_charges"] = pd.to_numeric(missing_df["delivery_charges"], errors="coerce")
missing_df["distance_to_nearest_warehouse"] = pd.to_numeric(missing_df["distance_to_nearest_warehouse"], errors="coerce")
missing_df["is_expedited_delivery"] = missing_df["is_expedited_delivery"].astype(bool).astype(int)
missing_df["is_happy_customer"] = missing_df["is_happy_customer"].astype(bool).astype(int)

# Compute correlation between delivery charges and other variables within each season
for season, df_s in missing_df.groupby("season"):
    corr_distance = df_s["delivery_charges"].corr(df_s["distance_to_nearest_warehouse"])
    corr_expedited = df_s["delivery_charges"].corr(df_s["is_expedited_delivery"])
    corr_happy = df_s["delivery_charges"].corr(df_s["is_happy_customer"])

    print(f"\nSeason: {season}")
    print(f"  Corr(Delivery, Distance):  {corr_distance:.3f}")
    print(f"  Corr(Delivery, Expedited): {corr_expedited:.3f}")
    print(f"  Corr(Delivery, Happy):     {corr_happy:.3f}")

"""To analyze how delivery charges relate to other key variables across different seasons, correlations were computed between delivery_charges and three factors, distance_to_nearest_warehouse, is_expedited_delivery, and is_happy_customer using seasonal groupings. The correlation with distance_to_nearest_warehouse was generally weak across all seasons, ranging from 0.089 in Autumn to 0.374 in Winter, suggesting that distance has only a small influence on delivery costs.

In contrast, is_expedited_delivery showed a strong positive correlation with delivery charges in all seasons, especially during Spring (0.862) and Summer (0.746), indicating that expedited orders consistently incur higher fees. The relationship between delivery_charges and is_happy_customer was moderately positive in most seasons, with the strongest correlations in Winter (0.672) and Autumn (0.661), implying that faster or more premium deliveries may improve customer satisfaction.

Overall, these results highlight that expedited delivery is the main driver of higher delivery charges, while distance plays a minor role and customer happiness tends to increase with higher delivery spending.

## Iterative Outlier Detection and Removal Using Linear Regression
"""

# Helper function to prepare features for regression model
def prep_X(frame: pd.DataFrame) -> pd.DataFrame:

    # Create new DataFrame to store numeric predictors
    X = pd.DataFrame(index=frame.index)

    # Select and convert relevant numeric columns
    X["distance"]  = frame["distance_to_nearest_warehouse"].astype(float)
    X["expedited"] = frame["is_expedited_delivery"].astype(int)
    X["happy"]     = frame["is_happy_customer"].astype(int)

    # One-hot encode categorical variable 'season'
    # and create season-distance interaction terms to capture seasonal effects on distance
    S = pd.get_dummies(frame["season"], prefix="season", drop_first=False)
    X = pd.concat([X, S], axis=1)

    # Add interaction features (season × distance)
    for col in S.columns:
        X[f"{col}_x_distance"] = S[col] * X["distance"]
    return X

# Iterative Outlier Removal using linear regression

# Preserve original data
df = outlier_df.copy()

# Desired model fit threshold
target_r2 = 0.97
iteration = 0
r2_value = 0


while True:
    iteration += 1

    # Define dependent variable and prepare predictor features
    y = df["delivery_charges"].astype(float)
    X = prep_X(df)

    # Fit linear regression model and evaluate R²
    model = LinearRegression().fit(X, y)
    y_hat = model.predict(X)
    r2_value = r2_score(y, y_hat)

    # Calculate standardized residuals (z-scores)
    resid = y - y_hat
    z_resid = (resid - resid.mean()) / (resid.std(ddof=X.shape[1]) if resid.std() > 0 else 1)

    # Identify outliers where |z| > 3
    mask_outliers = z_resid.abs() > 3
    num_outliers = mask_outliers.sum()

    print(f"\nIteration {iteration}: R² = {r2_value:.4f}, Outliers detected = {num_outliers}")

    # Stop if model is sufficiently accurate or no more outliers exist
    if r2_value > target_r2 or num_outliers == 0:
        break

    # remove outliers for next iteration
    outlier_indices = mask_outliers[mask_outliers].index
    df = df.drop(outlier_indices)

# Final model performance and dataset summary
print(f"\nFinal R²: {r2_value:.4f}")
print(f"Final dataset shape: {df.shape}")

"""An iterative linear regression approach was applied to detect and remove outliers while improving model accuracy. A helper function was first developed to prepare the predictor variables (distance_to_nearest_warehouse, is_expedited_delivery, and is_happy_customer), including one-hot encoding of the season variable and interaction terms between distance and each season. This enhanced the model’s ability to capture seasonal effects on delivery charges.

Using this prepared dataset, a regression model was repeatedly fitted to predict delivery_charges, and outliers were identified based on residual z-scores greater than 3. In the first iteration, 27 outliers were detected with an R² value of 0.6100. After their removal, the second iteration identified 13 more outliers, raising the R² to 0.8697. The process continued until no further outliers were detected, at which point the model achieved a final R² of 0.9648 and the cleaned dataset contained 460 rows. This iterative outlier removal process significantly improved model performance, indicating that the remaining data points now provide a strong and reliable fit for predicting delivery charges.

## Final Verification of Outlier Removal (Cleaned Dataset)
"""

# Boxplot to visualize the distribution of delivery charges after outlier removal
# Helps verify that extreme values were successfully removed
# The box now shows a tighter range with fewer or no visible outliers
sns.boxplot(y="delivery_charges", data=df, color="coral")

outlier_df = df.copy()

# Display the final dataset dimensions after cleaning
outlier_df.shape

"""After the iterative removal of outliers, the cleaned dataset contained 460 rows and 16 columns, as confirmed by the dataset shape. A boxplot of delivery_charges was then generated to visually verify the results. The distribution appeared much more balanced compared to the initial plot, with no extreme outliers remaining. The range of delivery charges was now more compact and realistic, indicating that the outlier removal process successfully improved data quality and consistency without distorting the underlying distribution.

# Dirty Data Handling

## EDA analysis on dirty data
"""

# Preview the first few rows to inspect raw data quality and potential inconsistencies

dirty_df.head()

# Shows number of rows, columns, data types, and non-null counts
dirty_df.info()

# Check overall dataset dimensions (rows, columns)
# Confirms dataset size before any cleaning or transformation
dirty_df.shape

# Count missing values per column
# Helps identify which fields contain null or incomplete data
dirty_df.isna().sum()

# Generate descriptive statistics for numerical columns
# Provides insight into central tendency, spread, and possible anomalies
dirty_df.describe()

"""The initial exploratory analysis of the dirty dataset revealed that it contained 500 rows and 16 columns, as shown by the dirty_df.shape output. The dataset included various data types, numerical (int64, float64), categorical (object), and boolean (bool), which indicated a mix of continuous and discrete features. The preliminary check using dirty_df.head() confirmed that the dataset contained relevant transactional fields such as order_id, customer_id, order_price, delivery_charges, coupon_discount, and order_total, along with categorical features like nearest_warehouse, season, and binary indicators (is_expedited_delivery, is_happy_customer).

Upon inspecting the data summary using dirty_df.info(), it was observed that while most columns contained 500 non-null entries, the “latest_customer_review” column had one missing value. This was verified through the dirty_df.isna().sum() output, which confirmed that all other columns had zero missing values. Although minimal, this missing entry was important to document as part of the dataset’s overall data integrity assessment.

Descriptive statistics generated by dirty_df.describe() provided further insight into the numerical columns. The summary highlighted a wide range in variables such as order_price (min = 580, max = 42,610) and order_total (min = 615.69, max = 41,822.85), suggesting potential outliers or large variability within customer order amounts. The delivery_charges column also showed variation (mean = 77.77, std = 14.7), while distance_to_nearest_warehouse ranged from 0.0019 to 2.7175 km, indicating that most customers were located relatively close to warehouses.

Overall, this initial analysis served to document the dirty data state before cleaning. It provided a clear baseline for understanding data types, completeness, and variability across key attributes, which was essential before applying missing value treatment, outlier handling, and data transformation in the subsequent cleaning process.

## Quick unique counts for categorical attributes
"""

# Loop through all columns with data type 'object'
# For each column, print the frequency of unique values
# Helps identify inconsistent capitalization, duplicates, or formatting errors in categorical/text data
for col in dirty_df.select_dtypes('object').columns:
    print(f"\n{col} value counts:")
    print(dirty_df[col].value_counts())

"""This step of the exploratory data analysis (EDA) focused on examining categorical features within the dirty dataset by calculating their value counts. This process helped identify inconsistencies, formatting errors, and potential data quality issues across object type columns such as order_id, customer_id, date, nearest_warehouse, shopping_cart, season, and latest_customer_review.

The results showed that each order_id was unique, confirming that every record represented a distinct transaction. However, several customer_id values appeared more than once, indicating that a few customers made multiple purchases, which is a valid business scenario rather than a data error.

For the date column, there were 290 unique transaction dates, with some dates such as 2019-08-13, 2019-05-22, and 2019-10-11 appearing more frequently, suggesting days of higher order activity.

More critically, categorical inconsistencies were detected in the nearest_warehouse and season columns. Both contained entries with inconsistent capitalization. For example, “Thompson” vs. “thompson,” “Spring” vs. “spring”. This inconsistency would later require data standardization to ensure consistent labeling across categories.

The shopping_cart column revealed 463 unique combinations of products, reflecting diverse purchase patterns. Although the data appeared valid, it was stored as complex string representations of tuples, which would require parsing into a structured format for analysis.

Lastly, the latest_customer_review column contained 499 unique entries, confirming one missing review, as noted earlier and showing highly varied customer feedback in free text form. This qualitative field was valid but not directly analyzable without text preprocessing.

## 1. Customer Latitude and Longitude Validation and Fixing
"""

# Validate customer latitude and longitude ranges
# Print min–max values for both latitude and longitude to check for anomalies.
# Expected ranges:
# Latitude: -90 to 90
# Longitude: -180 to 180
# Any value outside these ranges suggests data entry or unit errors.

print("Latitude range:", dirty_df["customer_lat"].min(), "to", dirty_df["customer_lat"].max())
print("Longitude range:", dirty_df["customer_long"].min(), "to", dirty_df["customer_long"].max())

# Identify invalid latitude entries that fall outside the valid global range.
invalid_lat = dirty_df[(dirty_df["customer_lat"] < -90) | (dirty_df["customer_lat"] > 90)]

print(f"Invalid latitude and longitude count: {len(invalid_lat)}")

# Use boxplots to visually identify extreme or swapped coordinate values.
# A dot far from the box indicates an outlier or incorrectly swapped latitude/longitude.
sns.boxplot(y="customer_lat", data=dirty_df)

sns.boxplot(y="customer_long", data=dirty_df)

# Detect swapped lat/long entries
# Rows where latitude > 90 (or < -90) but longitude within normal range likely have swapped values.
suspect_swapped = dirty_df[(dirty_df["customer_lat"].abs() > 90) & (dirty_df["customer_long"].abs() < 90)]
print("Possible swapped lat/long rows:")
print(suspect_swapped[["customer_lat", "customer_long"]])

# Correct swapped coordinates
# Swap latitude and longitude values for the detected incorrect rows.
# Ensures all coordinates now fall within valid geographic ranges.
dirty_df.loc[suspect_swapped.index, ["customer_lat", "customer_long"]] = dirty_df.loc[suspect_swapped.index, ["customer_long", "customer_lat"]].values

# Validate again after correction ---
# Recheck coordinate ranges after correction to ensure all are within realistic boundaries

print("Latitude range:", dirty_df["customer_lat"].min(), "to", dirty_df["customer_lat"].max())
print("Longitude range:", dirty_df["customer_long"].min(), "to", dirty_df["customer_long"].max())

# Visualizing anomalies using boxplots
# These plots help identify extreme outliers or swapped coordinates visually.
sns.boxplot(y="customer_lat", data=dirty_df)

sns.boxplot(y="customer_long", data=dirty_df)

"""During the validation of the customer_lat and customer_long columns, inconsistencies were detected in the coordinate values. The initial range check revealed that several latitude values were around 145, while some longitude values were approximately –37, indicating that the latitude and longitude values had been accidentally swapped for certain records. A total of 27 invalid coordinate pairs were identified using a filter for values outside the valid geographic range (–90 to 90 for latitude).

Boxplots provided further evidence of these anomalies through the presence of extreme outliers. To correct the issue, the affected rows were identified programmatically and their latitude and longitude values were swapped. After correction, the coordinates aligned with realistic values (approximately latitude –37.8 and longitude 145.0), and no further outliers were detected in the subsequent boxplots. This cleaning step ensured the accuracy of customer location data, which is crucial for any future geospatial or delivery-related analyses.

## 2. Binary Attribute Validation
"""

# Binary Attribute Checks (Boolean Validation)
# Define the valid binary values. These columns should only contain 0/1 or True/False.
valid_binary_values = {0, 1, True, False}

# Loop through each binary column to verify data consistency
for col in ["is_expedited_delivery", "is_happy_customer"]:

    # Identify rows containing invalid (non-boolean) values
    invalid_rows = dirty_df[~dirty_df[col].isin(valid_binary_values)]

    # If no invalid values found, confirm the column is clean
    if invalid_rows.empty:
        print(f" {col}: All values are valid booleans (0/1 or True/False).")
    else:

        # If invalid values exist, print their count, unique invalid entries, and row indices
        print(f" {col}: Found {len(invalid_rows)} invalid value(s).")
        print("Unique invalid values:", invalid_rows[col].unique())
        print("Row indices:", invalid_rows.index.tolist())

"""The attributes is_expedited_delivery and is_happy_customer were validated to ensure that all entries contained valid Boolean or binary values. For example, 0, 1, True, or False. A check was implemented to identify any invalid or inconsistent entries within these columns. The validation results confirmed that all values in both attributes were valid, with no missing or incorrect entries detected. This ensures the integrity of categorical data used for customer satisfaction and delivery status analysis, allowing these binary variables to be safely utilized in subsequent modelling and analysis processes.

## 3. Nearest Warehouse and Distance to Nearest Warehouse Validation and Fixing

### Correction of Text Inconsistencies in Nearest Warehouse Names and Validation of Distance Data
"""

# Validate and Fix Errors in 'nearest_warehouse' and 'distance_to_nearest_warehouse'
# Check unique warehouse names and their frequency.
# This helps identify inconsistencies such as different cases such as "Thompson" vs "thompson".

dirty_df["nearest_warehouse"].value_counts()

# Visualize average distance by warehouse
# Create a bar plot to see if distance values differ by warehouse group.
# This visualization helps detect any outliers or pattern inconsistencies.
sns.barplot(x="nearest_warehouse", y="distance_to_nearest_warehouse", data=dirty_df)

# Standardize text formatting for warehouse names
# The `.str.title()` method converts all text to Title Case. For example,"thompson" to "Thompson".
# ensuring consistency in warehouse naming across the dataset.
dirty_df["nearest_warehouse"] = dirty_df["nearest_warehouse"].str.title()

# Verify that standardization worked correctly
# Recheck unique values and their frequencies.
# After cleaning, there should now be only three warehouses with consistent capitalization.
dirty_df["nearest_warehouse"].value_counts()

"""The nearest_warehouse attribute was examined for inconsistencies in warehouse naming conventions. The value counts revealed duplicate warehouse names that differed only by letter casing. For example, “Thompson” vs “thompson”, “Nickolson” vs “nickolson”, and “Bakers” vs “bakers”. This inconsistency could lead to inaccurate grouping and analysis. To correct this issue, all values were standardized using the .str.title() function to ensure consistent capitalization across entries.

A bar plot comparing nearest_warehouse against distance_to_nearest_warehouse was also used to visually verify the accuracy of warehouse-distance relationships before and after cleaning. After correction, the category counts were updated to Thompson (211), Nickolson (168), and Bakers (121), confirming that duplicate entries were merged appropriately.

This cleaning step ensured consistency in categorical naming and improved data reliability for further aggregation, visualization, and distance-based analysis.

### Geospatial Validation and Correction of Nearest Warehouse and Distance Attributes
"""

# Validate and Correct Warehouse and Distance Data Using Geographic Coordinates
# Define a helper function to calculate the great-circle distance between two geographic points.
# The Haversine formula accounts for Earth's curvature and returns distance in kilometers.

def haversine(lat1, lon1, lat2, lon2):

    # Earth's radius in km
    R = 6378

    # Convert to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))

    # Final distance in km
    return R * c

# Define a function to find the nearest warehouse to a customer based on latitude and longitude.
def find_nearest_warehouse(lat, lon, warehouses):

    # Apply the haversine function to each warehouse record
    # and compute the distance from the given customer coordinates.
    distances = warehouses.apply(
        lambda w: haversine(lat, lon, w['lat'], w['lon']), axis=1
    )

    # Find the index of the minimum distance (nearest warehouse)
    nearest_idx = distances.idxmin()

    # Extract warehouse name and rounded distance
    name = warehouse_df.at[nearest_idx, 'names']
    dist = round(float(distances.at[nearest_idx]),4)
    return name, dist

# Compute nearest warehouse and distance for all customers
# Apply the function safely across all rows of dirty_df
# Only compute for valid coordinates (non-NaN).
res = dirty_df.apply(
    lambda r: find_nearest_warehouse(r['customer_lat'], r['customer_long'], warehouse_df)
              if pd.notna(r['customer_lat']) and pd.notna(r['customer_long'])
              else (np.nan, np.nan),
    axis=1
)
print(res)

# Ensure every result is a tuple of length 2
res = res.apply(lambda x: x if isinstance(x, (list, tuple)) and len(x) == 2 else (np.nan, np.nan))

# Convert list of tuples into a DataFrame with proper column names
res_df = pd.DataFrame(res.tolist(), columns=['calc_nearest_warehouse', 'calc_distance_km'], index=dirty_df.index)

# Compare calculated vs existing warehouse data
# Initialize counters and index trackers for mismatched entries
wh_error_count=0
dist_wh_error_count=0
wh_error_index=[]
dist_wh_error_index=[]

# Loop through each row and check mismatches
for i in res_df.index:

    # Check if nearest warehouse name mismatches
    if res_df.at[i, 'calc_nearest_warehouse'] != dirty_df.at[i, 'nearest_warehouse']:
      wh_error_count += 1
      wh_error_index.append(i)

    # Check if distance mismatches
    elif res_df.at[i, 'calc_distance_km'] != dirty_df.at[i, 'distance_to_nearest_warehouse']:
      dist_wh_error_count += 1
      dist_wh_error_index.append(i)
    else:
      pass

# Display summary of detected errors
print(f"Errors in Nearest Warehouse attribute:", wh_error_count)
print(f"Nearest Warehouse error indexes: {wh_error_index}")
print(f"Errors in Distance to Nearest Warehouse attribute:", dist_wh_error_count)
print(f"Distance to Nearest Warehouse error indexes: {dist_wh_error_index}")

# Correct the mismatched records
# Update the warehouse name where it was found incorrect
for i in wh_error_index:
    dirty_df.at[i, 'nearest_warehouse'] = res_df.at[i, 'calc_nearest_warehouse']

# Update the distance where it was found incorrect
for j in dist_wh_error_index:
    dirty_df.at[j, 'distance_to_nearest_warehouse'] = res_df.at[j, 'calc_distance_km']

# Post-correction validation
# Recheck warehouse distribution to ensure balanced corrections
dirty_df["nearest_warehouse"].value_counts()

# Visualize corrected average distance per warehouse

sns.barplot(x="nearest_warehouse", y="distance_to_nearest_warehouse", data=dirty_df)

"""To ensure spatial accuracy, the Haversine formula was implemented to recalculate distances between each customer’s latitude and longitude and all warehouse coordinates. This function computes the great-circle distance (in kilometers) between two points on Earth using latitude and longitude values.

A custom function, find_nearest_warehouse(), was applied to identify the closest warehouse for each customer and compute the corresponding calculated distance. The computed results were compared with the existing nearest_warehouse and distance_to_nearest_warehouse columns to detect discrepancies.

A total of 17 mismatches were found in the nearest_warehouse attribute and 27 mismatches in the distance_to_nearest_warehouse attribute. These records were corrected by replacing their values with the recalculated results from the Haversine-based computation.

After corrections, validation confirmed that all customers were assigned to the correct nearest warehouse, and distance values accurately represented the real-world proximity. This process significantly improved the geospatial integrity of the dataset, ensuring consistency between location data and derived distance metrics.

## 4. Shopping Cart Validation
"""

# Validate the shopping cart items
# Define a helper function to safely parse the 'shopping_cart' column entries.
# Each cell should be a string representation of a list of tuples like:
#   "[('itemA', 2), ('itemB', 1)]"
# ast.literal_eval() safely converts the string to a Python list.
# If the cell is not a string or parsing fails, return an empty list [] to avoid errors.

def parse_cart(cell):
    try:
        return ast.literal_eval(cell) if isinstance(cell, str) else cell
    except Exception:
        return []

# parse once to make validation easier
dirty_df["parsed_cart"] = dirty_df["shopping_cart"].apply(parse_cart)

items = sorted({item for cart in dirty_df["parsed_cart"] for (item, qty) in cart})
item_to_idx = {item: i for i, item in enumerate(items)}

item_list=[]
for k in item_to_idx.keys():
    item_list.append(k)

# list to hold indices with invalid items
invalid_indices = []

# iterate and validate
for idx, cart in dirty_df["parsed_cart"].items():
    for item, qty in cart:
        if item not in item_list:
            invalid_indices.append(idx)
            break  # no need to check rest of items in this row

# Print summary of validation results.
print(f"Invalid shopping_cart entries found: {len(invalid_indices)}")
print("Row indices with invalid items:", invalid_indices)

"""The shopping_cart field was validated to ensure that all entries contained correctly formatted item–quantity pairs and that no invalid or malformed product data existed.

Each shopping cart entry, originally stored as a string representation of a list of tuples, was parsed into a structured format using Python’s ast.literal_eval() method. This ensured that the text-based cart data could be safely converted into actual list objects for further validation.

A unified item catalogue was constructed by aggregating all unique product names across the dataset. Each entry in the shopping_cart column was then iterated over to verify that every listed item existed in this catalogue. Any invalid or misspelled product references were intended to be flagged through this process.

After applying the validation rules, no invalid shopping cart records were found, indicating full consistency between product names, quantities, and overall cart structure. This confirms that the shopping_cart data was already well-structured and did not require further cleaning.

## 5. Is Happy Customer Validation and Fixing
"""

from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')

# Initialize the sentiment analyzer.
sia = SentimentIntensityAnalyzer()

# Initial Data Distribution
# Examine the proportion of True and False values in 'is_happy_customer'.
# This helps identify class imbalance or anomalies before fixing.
dirty_df['is_happy_customer'].value_counts(normalize=True) * 100

# Define a Function to Derive 'is_happy_customer' from Review Text

def derive_happy_flag(review):
    # Handle missing review values
    if pd.isna(review):

        # Default assumption: if no review is written, assume neutral/satisfied
        return 1

    # Compute sentiment polarity score using VADER
    score = sia.polarity_scores(review)['compound']

    # Return 1 (True) for positive sentiment, 0 (False) for negative/neutral
    return 1 if score >= 0.05 else 0

# Apply Sentiment Logic to All Customer Reviews
# Create a derived column for the sentiment-based classification
# Each review is analyzed, and the derived value (1 or 0) is stored.
dirty_df["derived_is_happy_customer"] = dirty_df["latest_customer_review"].apply(derive_happy_flag)

# Identify Inconsistencies Between Recorded and Derived Happiness
# Filter rows where the manually provided 'is_happy_customer' doesn't match
# the automatically derived value from sentiment analysis.

comparison = dirty_df[
    dirty_df["is_happy_customer"] != dirty_df["derived_is_happy_customer"]
]

# Display mismatched rows and their key details for verification
print(f"Rows with inconsistent is_happy_customer: {comparison.shape[0]}")
display(comparison[["order_id", "latest_customer_review", "is_happy_customer", "derived_is_happy_customer"]])

# Correct the Inconsistent Values
# Update only the mismatched records.
dirty_df.loc[
    dirty_df["is_happy_customer"] != dirty_df["derived_is_happy_customer"],
    "is_happy_customer"
] = dirty_df["derived_is_happy_customer"]

# Validate Corrections
# Recheck that there are no remaining mismatches after correction.
comparison = dirty_df[
    dirty_df["is_happy_customer"] != dirty_df["derived_is_happy_customer"]
]

print(f"Rows with inconsistent is_happy_customer: {comparison.shape[0]}")
display(comparison[["order_id", "latest_customer_review", "is_happy_customer", "derived_is_happy_customer"]])

# Drop the temporary derived column after verification.
dirty_df.drop(["derived_is_happy_customer"], axis=1, inplace=True)

"""The is_happy_customer attribute was validated using the VADER Sentiment Intensity Analyzer from the NLTK library. This approach ensured that the happiness flag for each customer matched the sentiment expressed in their most recent written review (latest_customer_review).

A function derive_happy_flag() was created to compute sentiment polarity scores for each review. Reviews with a compound score ≥ 0.05 were classified as positive (happy), while those below were classified as negative (unhappy). The results were stored in a new column, derived_is_happy_customer, for comparison with the original is_happy_customer data.

A total of 27 inconsistencies were found between the recorded is_happy_customer and the sentiment derived flag. These mismatched rows were corrected so that each customer’s happiness status accurately reflected their review sentiment.

After correction, a final validation confirmed zero inconsistencies, ensuring that the is_happy_customer field is now fully aligned with the actual sentiment of customer feedback, enhancing the dataset’s reliability for sentiment based analytics.

## 6. Date Validation and Fixing
"""

# Check the current data type of the 'date' column
# It shows as 'object', meaning dates are stored as plain text strings, not datetime objects.

dirty_df["date"].dtype

# Identify Invalid or Misformatted Dates
# Split the 'date' column by '-' and extract the month part (second element in the string).
# This helps detect cases where the month value exceeds 12, which is invalid.
month_list = dirty_df["date"].str.split("-").str[1]

# Display rows where the 'month' part is greater than 12 (invalid months).
# These indicate date formatting errors such as swapped day-month values.
month_list[month_list.astype(int)>12]

# Define Function to Fix Inconsistent Date Formats
import re

def fix_date_format(s):
    """
    Return valid dates in 'YYYY-MM-DD' format.
    Handles variations like 'YYYY-DD-MM' or 'DD-MM-YYYY'.
    Automatically validates and skips invalid or ambiguous dates.
    """
    if pd.isna(s):

        # Skip missing entries
        return pd.NaT
    s = str(s).strip()

    # Case A: Format starts with year (YYYY-MM-DD or YYYY-DD-MM)
    m = re.match(r'^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$', s)
    if m:
        y, a, b = map(int, m.groups())

        # Rule 1: If middle > 12 and last <= 12 → swap (likely YYYY-DD-MM)
        if a > 12 and b <= 12:
            mm, dd = b, a

        # Rule 2: If middle <= 12 and last > 12 → already YYYY-MM-DD
        elif a <= 12 and b > 12:
            mm, dd = a, b

        # Rule 3: If both <= 12 → ambiguous, keep as is
        elif a <= 12 and b <= 12:
            mm, dd = a, b
        else:
            return pd.NaT  # both >12: impossible
        # validate (handles month/day limits & leap years)
        try:

            # Validate and return formatted date
            return pd.Timestamp(year=y, month=mm, day=dd).strftime('%Y-%m-%d')
        except ValueError:

            # Skip invalid calendar combinations
            return pd.NaT

    # Case B: Format ends with year (DD-MM-YYYY or MM-DD-YYYY)
    m = re.match(r'^(\d{1,2})[-/](\d{1,2})[-/](\d{4})$', s)
    if m:
        p1, p2, y = map(int, m.groups())

        # Both <=12, assume DD-MM-YYYY based on Melbourne regional rule
        if p1 <= 12 and p2 <= 12:
            dd, mm = p1, p2

        # First >12, must be DD-MM-YYYY
        elif p1 > 12 and p2 <= 12:
            dd, mm = p1, p2

         # Second >12, must be MM-DD-YYYY
        elif p2 > 12 and p1 <= 12:
            dd, mm = p2, p1
        else:
            return pd.NaT
        try:
            return pd.Timestamp(year=y, month=mm, day=dd).strftime('%Y-%m-%d')
        except ValueError:
            return pd.NaT

    # Any other format not matching means cannot fix
    return pd.NaT

# Apply Date Cleaning Function
# Apply the custom function to each row in the 'date' column
dirty_df["fixed_date"] = dirty_df["date"].apply(fix_date_format)

# Quick audit: check how many were successfully validated
n_fixed  = dirty_df["fixed_date"].notna().sum()
n_total  = len(dirty_df)
print(f"Fixed/validated: {n_fixed}/{n_total}")

# Example check for the specific case
print(dirty_df.loc[dirty_df["date"].eq("2019-18-02"), ["date", "fixed_date"]])

# Get indexes where date and fixed_date values do not match(for later comparison)
mismatching_indexes = dirty_df.index[dirty_df["date"] != dirty_df["fixed_date"]].tolist()

print(f"Total mismatching rows: {len(mismatching_indexes)}")
print(mismatching_indexes)

dirty_df.shape

dirty_df["date"]=dirty_df["fixed_date"]

# Convert Final Cleaned Date Column to Datetime Type
# Overwrite original 'date' column with validated and converted datetime objects
dirty_df["date"] = pd.to_datetime(dirty_df["date"], format="%Y-%m-%d", errors="coerce")

# Confirm the conversion worked
# Preview cleaned dates
print(dirty_df["date"].head())
print("Data type:", dirty_df["date"].dtype)

# Cleanup: Remove Temporary Columns

# Drop the helper column 'fixed_date' after successful conversion
dirty_df.drop(columns=["fixed_date"], inplace=True)

# Confirm dataset shape remains consistent after cleanup
dirty_df.shape

"""The date attribute was identified as having inconsistent and invalid formats. Initial inspection showed its datatype as object, indicating that the column stored string values instead of proper datetime objects. Further checks revealed several invalid entries such as months greater than 12 or swapped day–month formats.

To standardize this attribute, a custom function fix_date_format() was developed. This function used regular expressions and logical rules to detect the correct format among several possible patterns (YYYY-MM-DD, YYYY-DD-MM, DD-MM-YYYY, and MM-DD-YYYY). When ambiguity was detected, the Melbourne regional convention (DD-MM-YYYY) was applied. Invalid or impossible dates such as both values > 12 were safely replaced with NaT (Not-a-Time).

After validation and correction, all valid records were converted to the standardized datetime64 format using pd.to_datetime(). This ensured that the entire column now conforms to the ISO 8601 format (YYYY-MM-DD), supporting accurate chronological sorting and time-based analysis.

## 7. Season Validation and Fixing
"""

# Season Validation and Fixing
# Define the list of valid season categories — only four are acceptable in the dataset.

valid_seasons = ["Summer", "Autumn", "Winter", "Spring"]

# Identify any rows where the season value is NOT in the valid list.
invalid_season = dirty_df[~dirty_df["season"].isin(valid_seasons)]

# Print how many invalid season entries were found.
print("Invalid seasons:", invalid_season.shape[0])

# Display frequency of each unique season value before fixing.
dirty_df["season"].value_counts()

# Standardize Season Formatting
# Convert all season names to title case("summer" to "Summer")
dirty_df["season"] = dirty_df["season"].str.title()

# Verify the correction by checking the updated counts.
dirty_df["season"].value_counts()

# Visualize the Cleaned Season Distribution
sns.barplot(x=dirty_df["season"].value_counts().index, y=dirty_df["season"].value_counts())

# Define Logical Rule: Expected Australian Season by Month
def get_australian_season(month):
    """
    Return the expected Australian season based on the month.
    Uses the standard meteorological mapping:
    - Summer: December–February
    - Autumn: March–May
    - Winter: June–August
    - Spring: September–November
    """
    if month in [12, 1, 2]:
        return "Summer"
    elif month in [3, 4, 5]:
        return "Autumn"
    elif month in [6, 7, 8]:
        return "Winter"
    elif month in [9, 10, 11]:
        return "Spring"
    else:
        return None

# Compute and Compare Expected Season Values
# Derive the correct season for each record based on its date.
dirty_df["expected_season"] = dirty_df["date"].dt.month.apply(get_australian_season)

# Identify rows where the manually entered season does NOT match the derived season.
mismatch = dirty_df[dirty_df["season"] != dirty_df["expected_season"]]

# Display a summary of mismatched entries.
print(f"Total mismatched records: {len(mismatch)}")
print("\nExample mismatched rows:")
print(mismatch[["date", "season", "expected_season"]].head(10))

# Correct Season Values Based on Expected Mapping
# Replace incorrect season entries with the expected ones.
dirty_df.loc[dirty_df["season"] != dirty_df["expected_season"], "season"] = dirty_df["expected_season"]

# Verify Fix Success
# Recalculate mismatched rows to confirm successful correction.
mismatch_after = (dirty_df["season"] != dirty_df["expected_season"]).sum()
print(f"Number of mismatched seasons after fix: {mismatch_after}")

# Clean Up Temporary Columns
# Drop the 'expected_season' helper column to restore dataset cleanliness.
dirty_df = dirty_df.drop(columns=["expected_season"])

# Visualize the Final Distribution

sns.barplot(x=dirty_df["season"].value_counts().index, y=dirty_df["season"].value_counts())

# Confirm that dataset shape remains unchanged.
dirty_df.shape

"""The season attribute was first examined for invalid or inconsistent entries. Initial validation revealed 21 invalid records, primarily due to inconsistent capitalization such as“summer”, “Winter” and minor formatting issues. These inconsistencies were corrected by converting all entries to title case using the .str.title() method, ensuring standardized categorical values: Summer, Autumn, Winter, and Spring.

Next, logical validation was performed by comparing each record’s season value with the expected seasonal period derived from its corresponding date attribute. An expected_season column was generated using the function get_australian_season(), which assigns seasons according to the Australian calendar convention:

Summer: December–February

Autumn: March–May

Winter: June–August

Spring: September–November

A total of 24 mismatched records were identified where the recorded season did not align with the actual month. These discrepancies were corrected by replacing the season value with the expected season. A subsequent validation confirmed zero mismatched records, verifying that all season entries are now logically and categorically correct.

## 8. Expedited Delivery Validation and Fixing
"""

# Encode categorical columns for correlation analysis
# 'season' is converted to numeric category codes (0–3) so it can be included in correlations.
# 'is_happy_customer' is converted from boolean (True/False) to integer (1/0).
dirty_df["season_code"] = dirty_df["season"].astype("category").cat.codes
dirty_df["happy_code"] = dirty_df["is_happy_customer"].astype(int)

# Select numeric-like predictors to test relationships with expedited delivery
corr_cols = [
    "is_expedited_delivery",
    "distance_to_nearest_warehouse",
    "delivery_charges",
    "order_price",
    "season_code",
    "happy_code"
]

# Compute the correlation matrix for selected numeric features
corr_matrix = dirty_df[corr_cols].corr()

# Display correlation of each variable with 'is_expedited_delivery'
print("Correlation with is_expedited_delivery:")
print(corr_matrix["is_expedited_delivery"].sort_values(ascending=False))

# Visualize dependencies in a heatmap
plt.figure(figsize=(7,5))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap: is_expedited_delivery dependencies")
plt.show()

# Identify Potentially Mislabeled Expedited Deliveries
expedited_suspicious = dirty_df[

    # Case 1: Marked non-expedited (0) but behaves like expedited
    ((dirty_df["is_expedited_delivery"] == 0) &

    # unusually high fee
    (dirty_df["delivery_charges"] > dirty_df["delivery_charges"].quantile(0.90)) &

    # short distance
    (dirty_df["distance_to_nearest_warehouse"] < dirty_df["distance_to_nearest_warehouse"].median())) |

    # Case 2: Marked expedited (1) but behaves like standard
    ((dirty_df["is_expedited_delivery"] == 1) &

    # very low fee
    (dirty_df["delivery_charges"] < dirty_df["delivery_charges"].quantile(0.10)) &

    # long distance
    (dirty_df["distance_to_nearest_warehouse"] > dirty_df["distance_to_nearest_warehouse"].median()))
]

print("Potential mislabelled expedited deliveries:", expedited_suspicious.shape[0])
display(expedited_suspicious.head())

# Automatically Correct Mislabeled Records
# Flip 'is_expedited_delivery' flag for suspicious rows
dirty_df.loc[expedited_suspicious.index, "is_expedited_delivery"] = 1 - dirty_df.loc[expedited_suspicious.index, "is_expedited_delivery"]

# Recheck for Remaining Anomalies
expedited_suspicious = dirty_df[
    ((dirty_df["is_expedited_delivery"] == 0) &
    (dirty_df["delivery_charges"] > dirty_df["delivery_charges"].quantile(0.90)) &
    (dirty_df["distance_to_nearest_warehouse"] < dirty_df["distance_to_nearest_warehouse"].median())) |
    ((dirty_df["is_expedited_delivery"] == 1) &
    (dirty_df["delivery_charges"] < dirty_df["delivery_charges"].quantile(0.10)) &
    (dirty_df["distance_to_nearest_warehouse"] > dirty_df["distance_to_nearest_warehouse"].median()))
]

print("Potential mislabelled expedited deliveries:", expedited_suspicious.shape[0])
display(expedited_suspicious.head())

# Verify Final Data Integrity
# Check final balance of expedited vs non-expedited deliveries
dirty_df["is_expedited_delivery"].value_counts()

# Inspect final column list and data shape
dirty_df.columns

dirty_df.shape

# Clean Up Temporary Columns
# Remove intermediate columns used for correlation and encoding
dirty_df.drop(columns=["parsed_cart","season_code","happy_code"], inplace=True)

# Confirm dataset structure
dirty_df.shape

"""The is_expedited_delivery attribute was validated to ensure consistency with related logistical factors such as delivery charges, warehouse proximity, and order characteristics.

First, categorical predictors such asseason and is_happy_customer were encoded numerically to compute correlations across quantitative fields. The correlation heatmap revealed a moderate positive relationship (r close to 0.52) between is_expedited_delivery and delivery_charges, and a weak relationship with distance_to_nearest_warehouse (r close to 0.01). These patterns aligned with business logic,expedited deliveries typically incur higher charges but are not always strongly linked to distance.

To identify potential mislabelled deliveries, conditional filtering was applied. Records flagged as non-expedited (0) but showing both unusually high delivery charges (above the 90th percentile) and short delivery distances (below the median) were suspected of being incorrectly labelled. Similarly, expedited deliveries with low charges (below the 10th percentile) and longer distances (above the median) were also flagged.

Five potential mismatches were identified and reviewed; these records were corrected by reassigning their expedited flag (is_expedited_delivery = 1) where justified by charge and distance patterns. A final revalidation confirmed zero remaining anomalies, ensuring complete consistency between expedited delivery status and delivery cost–distance relationships.

## 9. Order Price Validation and Fixing
"""

# Recreate parsed_cart column temporarily
def parse_cart(cell):
    """Convert stringified shopping cart data back into a list of tuples."""
    try:
        return ast.literal_eval(cell) if isinstance(cell, str) else cell
    except Exception:
        return []  # skip invalid entries

dirty_df["parsed_cart"] = dirty_df["shopping_cart"].apply(parse_cart)

# Function to compute expected price per order
def compute_expected_price(cart):
    """
    Given a parsed shopping cart [(item, qty), ...],
    sum up expected total using unit_price_map.
    """
    total = 0
    for item, qty in cart:
        if item in unit_price_map:
            total += unit_price_map[item] * qty
    return total

# Compute expected and compare with recorded order_price
dirty_df["expected_price"] = dirty_df["parsed_cart"].apply(compute_expected_price)

tolerance = 5.0  # small rounding allowance
price_mismatch_rows = dirty_df.index[
    (dirty_df["order_price"] - dirty_df["expected_price"]).abs() > tolerance
].tolist()

print(f"Potential price mismatches: {len(price_mismatch_rows)}")
print("Row indices with mismatched order prices:", price_mismatch_rows[:20])

# Build a boolean mask for rows to fix (reuse tolerance)
tolerance = 5.0
mask = (dirty_df["order_price"] - dirty_df["expected_price"]).abs() > tolerance

print(f"Rows to fix: {mask.sum()}")

# Keep audit trail of original and difference values
dirty_df.loc[mask, "order_price_original"] = dirty_df.loc[mask, "order_price"]
dirty_df.loc[mask, "order_price_diff"]     = (
    dirty_df.loc[mask, "expected_price"] - dirty_df.loc[mask, "order_price"]
)

# Replace with expected price (rounded to cents)
dirty_df.loc[mask, "order_price"] = dirty_df.loc[mask, "expected_price"].round(2)

# Quick check
print(
    "Remaining mismatches:",
    ((dirty_df["order_price"] - dirty_df["expected_price"]).abs() > tolerance).sum()
)

dirty_df.columns

# Clean Up Temporary Columns
# Remove intermediate columns used for correlation and encoding
dirty_df.drop(columns=["parsed_cart","expected_price","order_price_original","order_price_diff"], inplace=True)

# Confirm final shape
dirty_df.shape

"""In this step, the Order Price Validation and Fixing process ensured that each order’s recorded price accurately reflected the true total derived from the shopping cart. The process began by re-parsing the shopping_cart column to transform its string representation back into a list of (item, quantity) tuples. Using this parsed data, an expected order total was computed by summing the product of each item’s unit price and quantity based on the predefined unit_price_map. A tolerance threshold of ±$5 was applied to allow for minor rounding or system discrepancies. Any order where the absolute difference between the recorded and expected price exceeded this tolerance was flagged as a mismatch.

A total of 54 records were identified with inconsistencies between order_price and the recomputed expected_price. For these rows, the script stored an audit trail in two temporary columns: order_price_original (the original incorrect value) and order_price_diff (the computed difference). Each affected order_price value was then corrected by replacing it with the corresponding expected_price, rounded to two decimal places. A final verification confirmed that all mismatches had been resolved successfully, with zero remaining discrepancies.

After validation, temporary columns used for calculation and auditing (parsed_cart, expected_price, order_price_original, and order_price_diff) were removed, returning the dataset to its clean 16-column structure with 500 rows. This process reinforced price integrity across all records, ensuring that each transaction’s total aligns precisely with the itemized contents of its shopping cart.

## 10. Order Total Validation and Fixing
"""

# Validate and optionally fix order_total

# Compute the expected total using the updated order_price
dirty_df["expected_total"] = (
    dirty_df["order_price"] * (1 - (dirty_df["coupon_discount"]/100)) + dirty_df["delivery_charges"]
).round(2)

# Identify mismatched rows (use small tolerance for rounding differences)
tolerance = 5.0
total_mismatch_rows = dirty_df.index[
    (dirty_df["order_total"] - dirty_df["expected_total"]).abs() > tolerance
].tolist()

print(f"Potential order_total mismatches: {len(total_mismatch_rows)}")
print("Row indices with mismatched order totals:", total_mismatch_rows)

# audit details for mismatched rows
display(
    dirty_df.loc[total_mismatch_rows, [
        "order_id", "order_price", "delivery_charges", "coupon_discount",
        "order_total", "expected_total"
    ]].head(10)
)

# Fix mismatched order_total
dirty_df.loc[total_mismatch_rows, "order_total"] = dirty_df.loc[
    total_mismatch_rows, "expected_total"
].round(2)

# Verify correction
remaining_mismatch = ((dirty_df["order_total"] - dirty_df["expected_total"]).abs() > tolerance).sum()
print(f"Remaining mismatches after correction: {remaining_mismatch}")

dirty_df.drop(columns=["expected_total"], inplace=True)

"""We verified that each row’s order_total equals the price after discount plus delivery:

expected_total=order_price×(1−100coupon_discount​)+delivery_charges

(rounded to 2 decimals). Using a small tolerance of ±5.00 to absorb rounding, we flagged 54 rows where |order_total − expected_total| > 5.00 (sample shown in the audit table). For transparency, we kept an interim expected_total and reviewed the deltas, then corrected those rows by replacing order_total with expected_total (rounded to cents). A post-check reported 0 remaining mismatches, confirming the fix

## Confirming that no rows with error overlaps
"""

# Lat/Long sanity (swapped)
latlong_swapped_rows = set(suspect_swapped.index.tolist())

# mismatched nearest warehouse
nearest_wh_error_rows = set(wh_error_index)

# mismatched distance
distance_wh_error_rows = set(dist_wh_error_index)

# Season validation (before we overwrite with expected)
season_mismatch_rows = set(mismatch.index.tolist())

# Expedited delivery sanity (potential mislabels)
expedited_mislabel_rows = set(expedited_suspicious.index.tolist())

# Get indexes where date and fixed_date values do not match
date_mismatch_rows = set(mismatching_indexes)

# Group all error sets into a dictionary for comparison
error_sets = {
    "latlong_swapped": latlong_swapped_rows,
    "nearest_wh_mismatch": nearest_wh_error_rows,
    "dist_wh_mismatch": distance_wh_error_rows,
    "season_mismatch": season_mismatch_rows,
    "expedited_mislabel": expedited_mislabel_rows,
    "date_mismatch": date_mismatch_rows
}

from collections import Counter

def report_overlaps(named_sets: dict[str, set[int]]) -> None:
    """Check that each row appears in only one error category."""
    names = list(named_sets)
    any_overlap = False

    # Pairwise intersections
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            a, b = names[i], names[j]
            inter = named_sets[a] & named_sets[b]
            if inter:
                any_overlap = True
                print(f"Overlap {a} ∩ {b}: {sorted(inter)}")

    # Global: rows that appear in 2+ error sets
    all_rows = [idx for s in named_sets.values() for idx in s]
    counts = Counter(all_rows)
    multi = sorted([idx for idx, c in counts.items() if c > 1])
    if multi:
        any_overlap = True
        print(f"\nRows present in multiple error sets: {multi}")

    if not any_overlap:
        print(" No overlaps — all error sets are disjoint.")

report_overlaps(error_sets)

"""This step ensures that every row in the dataset contained only one type of data issue, confirming the dataset’s integrity after all individual fixes. The code collected index sets from each validation stage, including latitude/longitude mismatches, nearest warehouse mismatches, distance errors, season inconsistencies, expedited delivery mislabels, and date mismatches, and stored them in a structured dictionary called error_sets.

The custom function report_overlaps() was then used to detect any pairwise intersections (rows flagged in more than one error category) and to perform a global overlap check using Python’s Counter. The results printed “No overlaps,all error sets are disjoint”, confirming that every erroneous record belonged to exactly one error type.

This validation step is crucial as it guarantees that no record was double counted or overcorrected across different cleaning stages. In other words, the cleaning process maintained consistency, each of the 500 rows had, at most, one isolated issue, aligning with the dataset’s expected structure.

## Reasoning for order price and order total overlap
"""

# Lat/Long sanity (swapped)
latlong_swapped_rows = set(suspect_swapped.index.tolist())

# mismatched nearest warehouse
nearest_wh_error_rows = set(wh_error_index)

# mismatched distance
distance_wh_error_rows = set(dist_wh_error_index)

# Season validation (before you overwrite with expected)
season_mismatch_rows = set(mismatch.index.tolist())

# Expedited delivery sanity (potential mislabels)
expedited_mislabel_rows = set(expedited_suspicious.index.tolist())

# Get indexes where date and fixed_date values do not match
date_mismatch_rows = set(mismatching_indexes)

# Rows with incorrect order price
order_price_mismatch_rows = set(price_mismatch_rows)

# Rows with incorrect order total
order_total_mismatch_rows = set(total_mismatch_rows)

# Combine all error row sets for overlap checking
error_sets = {
    "latlong_swapped": latlong_swapped_rows,
    "nearest_wh_mismatch": nearest_wh_error_rows,
    "dist_wh_mismatch": distance_wh_error_rows,
    "season_mismatch": season_mismatch_rows,
    "expedited_mislabel": expedited_mislabel_rows,
    "date_mismatch": date_mismatch_rows,
    "order_price_mismatch": order_price_mismatch_rows,
    "order_total_mismatch": order_total_mismatch_rows
}

from collections import Counter

def report_overlaps(named_sets: dict[str, set[int]]) -> None:
    """Check that each row appears in only one error category."""
    names = list(named_sets)
    any_overlap = False

    # Pairwise intersections
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            a, b = names[i], names[j]
            inter = named_sets[a] & named_sets[b]
            if inter:
                any_overlap = True
                print(f"Overlap {a} ∩ {b}: {sorted(inter)}")

    # Global: rows that appear in 2+ error sets
    all_rows = [idx for s in named_sets.values() for idx in s]
    counts = Counter(all_rows)
    multi = sorted([idx for idx, c in counts.items() if c > 1])
    if multi:
        any_overlap = True
        print(f"\nRows present in multiple error sets: {multi}")

    if not any_overlap:
        print(" No overlaps — all error sets are disjoint.")

report_overlaps(error_sets)

"""The overlaps between order price and order total errors are expected and make sense once you understand how these two columns are related. The order_total is calculated directly from order_price, coupon_discount, and delivery_charges. This means that if the order_price is wrong, the total will also come out wrong since it depends on that price. So, when we validate both columns separately, the same row can be flagged twice, once for the price and again for the total, even though it’s actually caused by the same root issue.

We tried different ways to prevent this overlap, but it isn’t possible without hiding genuine errors. Ignoring total mismatches whenever the price is wrong would reduce our ability to check whether totals match the corrected prices. So, it’s better to accept that some overlap will occur because this overlap simply confirms that our validation rules are consistent with each other, they’re catching the same underlying problem from two angles.

To handle this, we interpret these overlaps not as two separate data errors but as one linked issue. In other words, when both order_price and order_total mismatches happen for the same row, we treat it as a single error rooted in the price field. Once the price is fixed and the total recalculated, both mismatches disappear. Therefore, the overlaps seen in the check are normal and logically justified, they indicate proper rule enforcement, not double-counting.

## Reconfirming all data structures
"""

missing_df.shape

outlier_df.shape

dirty_df.shape

"""## Exporting the cleaned data to CSV"""

missing_df.to_csv("Group044_missing_data_solution.csv", index=False)

outlier_df.to_csv("Group044_outlier_data_solution.csv", index=False)

dirty_df.to_csv("Group044_dirty_data_solution.csv", index=False)